server:
  port: 8080
spring:
  data:
    mongodb: 
      uri: mongodb://admin:adminadmin@mongodb-shard-00-00-dqcnw.mongodb.net:27017,mongodb-shard-00-01-dqcnw.mongodb.net:27017,mongodb-shard-00-02-dqcnw.mongodb.net:27017/test?ssl=true&replicaSet=MongoDB-shard-0&authSource=admin&retryWrites=true
      grid-fs-database: images
logging:
  level:
    com.example: DEBUG
    org.springframework.web: DEBUG